aditoserversnmp:
  image: aditosnmp
  hostname: snmp
  environment:
    - LOOPTIME=2m
    - MONITORING_GROUP=adito
    - MONITORING_API_USER=APIUSER
    - HOSTNAME=b9c2911b0f66
    - TEPLATEHOST=passive-host
    - MONITORING_API_URL=monitoring.example.com
    - MONITORING_API_PORT=5665
    - ADITO_SNMP_COMMUNITY=public
    - ADITO_SNMP_PORT=161
    - TEMPLATESERVICE=passive-service
    - MONITORING_API_PASS=API_PASS
    - ADITO_SNMP_SERVER_ADDR=adito_address_SNMP
    - MEMORY_WARN_VALUE=95 
    - MEMORY_CRIT_VALUE=99
    - ADITO_SERVER_NAME=aditoServer
    - ADITO_SERVER_DISPLAY_NAME=Adito Server
  restart: unless-stopped